PHP 8.1 deprecated warning
thephpleague/commonmark pull request #762
Opened 2021-12-03 14:58 UTC by ElGigi

Prevent deprecated warning on ArrayAccess with PHP 8.1

2021-12-03 20:49 UTC, GrahamCampbell requested changes
Only the annotation on `offsetGet` is needed.

2021-12-03 20:49 UTC, GrahamCampbell commented on src/Util/ArrayCollection.php
> +    #[\ReturnTypeWillChange]
This line is not needed. The return type is already `void`.

2021-12-03 20:49 UTC, GrahamCampbell commented on src/Util/ArrayCollection.php
> +    #[\ReturnTypeWillChange]
This line is not needed. The return type is already `bool`.

2021-12-03 20:49 UTC, GrahamCampbell commented on src/Util/ArrayCollection.php
> +    #[\ReturnTypeWillChange]
This line is not needed. The return type is already `void`.

2021-12-03 23:06 UTC, ElGigi commented
Sorry, changed! A little too fast in my modification.

2021-12-04 23:23 UTC, GrahamCampbell approved these changes

2021-12-05 18:03 UTC, colinodell approved these changes
Thanks!

2021-12-05 18:03 UTC, merged